### ISSUE TITLE
[새 기능] 채널 지정 기능

### ISSUE THREAD

**Issue by Sharlottes** [Sharlottes/thefinalsbot#5]
![image](https://github.com/Sharlottes/thefinalsbot/assets/60801210/b1dc6a99-e252-492e-a2ee-05af6ac5c3db)

환경변수로 채널 지정하는건 귀찮고 유지보수적으로 나쁘다.
값마다 채널을 지정하고 일괄 편집 기능을 만들어야 함.
설정 데이터는 mongo db에다가 저장

**Checklist**
* [x] - 채널 지정 가능
* [x] - 일괄 설정 가능

**Comment by Cupelt** [comment]
db에 clientId항목을 추가하여 클라이언트마다 지정할 수 있게 하면 어떨까용

+ 확장성과, 테스트 편의성을 위해, 채널지정 명령어도 따로 빼 놓으면 좋구요

**Comment by Sharlottes** [comment]
> db에 clientId항목을 추가하여 클라이언트마다 지정할 수 있게 하면 어떨까용
> 
> + 확장성과, 테스트 편의성을 위해, 채널지정 명령어도 따로 빼 놓으면 좋구요

아 안그래도 테스트봇끼리 겹치는걸 우려해서 botId를 저장케 하고 있습니다.
말씀하신 채널지정 명령어는 필수적이라 봐서 개발 중에 있어용

**Comment by Sharlottes** [comment]
원래 DB에 직접 document를 insert하려 했지만 봇과 서버가 늘어난 이상 힘들다고 생각합니다.
서버 설정이 nullable하도록 바꾼다면 수많은 유효성 검사가 코드 곳곳에 흩어질게 뻔했고, 이 상태로는 서버 설정의 초기화를 위해 서버 설정이 필요하단 모순에 도달합니다.

이 이슈를 해결하다가 파편적인 변경 사항이 발생해선 안되므로 서버 설정 getter는 nullable하지 않아야 합니다. 하지만 서버 설정 자체는 nullable할 수 밖에 없습니다. 이 모순은 getter가 null 검사로 에러를 던지고 서버 설정을 non-nullable하다고 단언함으로써 해결합니다. 

또한 서버 설정이 nullable함으로써 발생하는 문제를 막기 위해 서버 설정을 쓰는 곳만 부분적으로 통제하는 것은 복잡합니다. (초기화 때 발생하는건 막더라도 런타임 때 터지는건 답도 없습니다. 결국 파편적인 변경 사항이 발생합니다.) 그러니 서버 설정이 없다면 그 서버에서 봇이 작동하지 않게 하는게 편합니다.

그러니 서버 주인 입장에선:
1. 봇이 초기화됩니다. 
2. 각 서버들을 초기화하다가 이 서버에 서버 설정이 없는 것을 확인합니다.
3. 관리자-전용 채널이 생성되고 서버 주인이 멘션됩니다.
4. 서버 주인은 서버 설정 버튼을 눌러 서버 설정 절차를 밟고 성공적으로 서버 설정을 완료합니다.
5. 봇은 서버 설정이 생김을 확인하고 해당 서버만 다시 초기화합니다.
6. 이제 이 서버에서 봇이 성공적으로 작동합니다!
7. 서버 주인은 채널을 다시 바꾼다면 서버 주인은 `/서버 설정`을 통해 (기존값이 기본값인 체로) 서버 설정 절차를 다시 밟게 됩니다.
 
와 같은 순서로 진행하게 됩니다.
즉, 서버 설정이 함수로 추출되고 초기화되지 못한 서버들은 서버 설정 외 기능이 작동되지 않게끔 바꾸면 됩니다.
